### ISSUE TITLE
pallet-dispute

### ISSUE THREAD

**Issue by f-gate** [ImbueNetwork/imbue#131]
# Pallet Dispute

## Objectives
- Provide a system whereby a jury of accounts can decide the outcome of a dispute over services.
- Incentivise the jury allowing a simple form of income.??
- Allow for the fair dispute of briefs with a single owner.

### Raising a dispute
- [x] One of 2 parties can raise a dispute at any time (timings and possibility to dispute are dictated by pallet proposals).
- [x] The dispute must contain what exactly is being disputed on and who is disputing (Preferably as a generic). (Could be a set of milestones or a single milestone)
- [x] Disputes are finalised on a future block as defined in the config.

### Voting on a dispute
- [x] Anyone of the jury can vote either for or against a dispute. 
- [x] Votes are mutable.
- [x] Autofinalise on unanimous voting.
- [x] The ability to extend the voting period just once. 

### Finalising a dispute
- [x]  Call a hook on_completed_dispute() which will allow either party to withdraw or refund the amount.
- [ ]  allow the correct party to refund or withdraw from pallet-proposals only out of unapproved milestones (for obvious reasons)

## Refactors Required
In this PR we also need to depricate the use of funding type in favor of a new more flexibly alternative. For more details see: https://github.com/ImbueNetwork/imbue/issues/193.

## Future Ideas
- If either party is not happy with the outcome, they can pay more for it to go to a larger jury or higher ranking officials.
- Roles specifically for a judge or something.
- Declining the invitation to handle a dispute + slashing.

**Comment by mshankarrao** [comment]
> 
From top to bottom
1)when we say here Jury of trusted accounts can decide, it means one of the handler(which was chosen while submitting the dispute) correct?
2) Incentivising to one of the handlers?
3) Briefs with single owner meaning? Isn't most of the briefs will have single owner
4) Do we need to work on creating the config and work on this first https://github.com/ImbueNetwork/imbue/issues/193

**Comment by f-gate** [comment]
Updated to display the new thinking around jury selection
