### ISSUE TITLE
Reset voting if all votes are done 

### ISSUE THREAD

**Issue by ssani7** [ImbueNetwork/imbue#263]
currently the voting only closes if the yes / no vote reaches 75%. but say all the approvers have voted and both yes and no votes are 50%. In this case this should close the voting and reject the milestone . So please add a check to see if all the votes are done for a milestone and if the yes is not 75% then close the voting round and reject the milestone.

**Comment by mshankarrao** [comment]
@ssani7 this is already closed and is being covered in issue #264 by @f-gate. Shall we close this issue as well?

**Comment by f-gate** [comment]
@mshankarrao The other issue was a duplicate! this hasnt been completed yet

**Comment by mshankarrao** [comment]
Ok sure @f-gate
