### ISSUE TITLE
The difficulties of refunding users

### ISSUE THREAD

**Issue by f-gate** [ImbueNetwork/imbue#65]
A continuation of PMs: 

I'm tying to benchmark the refund extrinsic with great pain, the issues are that: 
- We have an unbounded amount of contributors on a given project therefore an unbounded loop to refund.
- There's not a clear way of dynamically setting the weight based on number of contributors.

Since the worst case scenario is unbounded it is therefore impossible to benchmark.

Solutions? 
- Bounding # of contributors, This will impose that calling refunds will be extremely expensive for projects with a small # of contributors.

perhaps this can be avoided in combination with:
  
- Refunding users using on_initialise:  Instead of explicitly doing the refunds in the method, the method will only calculate the required transfers and place into storage (temporarily). Then in the next block's on_initialise the refunds are carried out and the weight can be set dynamically (x w/r per refund). 

Or 

- Somehow deducting the fee from the refund pot mitigating the cost from a single individual.

If we are happy with simply bounding # of contributors then this will be the simplest solution at the expense of contributors.
Otherwise doing such a loop in the on initialise may leave us open for attack if malicious contributes projects decide to refund all at once.

**Comment by f-gate** [comment]
I believe we have agreed that: 

- Bounding is necessary.
- There are options for using hooks to make the process cheaper.

**Comment by samelamin** [comment]
We need to bound contributors, either way I suggest an upper limit of 5k for now 

Re refund, I want to explore having a queue of contributors requiring refunds. A hook for each block could work but we have to be careful about tracking refunds and batch them, say 10-20 contributors per block

Once we complete all the required funders, we mark the project as refunded

**Comment by f-gate** [comment]
Agreed on this, perhaps we can use the block's on_idle() hook to refund when theres extra block space?
